%Kevin Claytor
%October 2006
%
%SodokuSolver.m
%
%Usage; SodokuSolve(action)
%  Calling SodokuSolve (no argument) will launch a GUI that you can then use to solve a
%     Sodoku.  Action is used primarially for call backs.
%  This just builds the 9x9 matrix A to send to SudokuCore, see type
%    "help sudokucore" for more information
%

%Glossary
% Yeah, okay 81 variable text boxes that I'm not going to idiot proof,
%   darnit.  If you can't type the correct numbers in, that's your problem
%

%Pseudocode
%  Initialize our GUI
%   make the boxes
%   get the info from the boxes
%   build matrix A
%   solve matrix A
%   print the solved sudoku on the grid
%

function SudokuSolver(action)

if nargin<1                                 % If number of arguments input < 1
    action = 'initialize';
end

if strcmp(action,'initialize')  
    title='Sudoku Solver';  % Title our graph, use a variable that we can later change
    figure('Name',title,...
           'NumberTitle','off', ...
	       'DoubleBuffer','on');   % turn off that flickering
    
    % Start Pushbutton
    uicontrol('Style','PushButton',...
              'String','Solve!',...  % Initial label on button
              'Position',[10 30 80 50],... % Position in pixel units
              'Callback','SudokuSolver(''start'')',... % What clicking on the button does
              'Tag','Control');              % Control name

    %A frame to enclose everything
    uicontrol('Style','Frame',...
              'Position',[130 50 360 360]);
    %Four frames to sub-divide the large frame into the classic grid of 3 by 3
    uicontrol('Style','Frame',...
              'Position',[250 290 120 120]);
    uicontrol('Style','Frame',...
              'Position',[130 170 120 120]);
    uicontrol('Style','Frame',...
              'Position',[370 170 120 120]);
    uicontrol('Style','Frame',...
              'Position',[250 50 120 120]);

    %An instructions box
    uicontrol('Style','Text',...           % Boring text box
              'String',sprintf('Type in numbers in their location.\nUse 0 to represent a blank spot.\nWhen you are ready, press Solve to generate the solution.\n'),...
              'Position',[10 230 90 120],...
              'Tag','Gen_Label');
          
    % An about dialouge
    uicontrol('Style','PushButton',...
        'String','About',...
        'Position',[10 1 50 15],...
        'Callback','SudokuSolver(''about'')',... % give our about message
        'Tag','About');

    
%%ROW 1
    uicontrol('Style','Edit',...           % Cell 1,1
              'String','0',...
              'Position',[140 370 30 30],...
              'Tag','11');
    uicontrol('Style','Edit',...           % Cell 1,2
              'String','0',...
              'Position',[175 370 30 30],...
              'Tag','12');
    uicontrol('Style','Edit',...           % Cell 1,3
              'String','0',...
              'Position',[210 370 30 30],...
              'Tag','13');
          
    uicontrol('Style','Edit',...            % Cell 1,4
              'String','0',...
              'Position',[260 370 30 30],...
              'Tag','14');
    uicontrol('Style','Edit',...           % Cell 1,5
              'String','0',...
              'Position',[295 370 30 30],...
              'Tag','15');
    uicontrol('Style','Edit',...           % Cell 1,6
              'String','0',...
              'Position',[330 370 30 30],...
              'Tag','16');
          
   uicontrol('Style','Edit',...             % Cell 1,7
              'String','0',...
              'Position',[380 370 30 30],...
              'Tag','17');
    uicontrol('Style','Edit',...           % Cell 1,8
              'String','0',...
              'Position',[415 370 30 30],...
              'Tag','18');
    uicontrol('Style','Edit',...           % Cell 1,9
              'String','0',...
              'Position',[450 370 30 30],...
              'Tag','19');
          
%%ROW 2
    uicontrol('Style','Edit',...           % Cell 2,1
              'String','0',...
              'Position',[140 335 30 30],...
              'Tag','21');
    uicontrol('Style','Edit',...           % Cell 2,2
              'String','0',...
              'Position',[175 335 30 30],...
              'Tag','22');
    uicontrol('Style','Edit',...           % Cell 2,3
              'String','0',...
              'Position',[210 335 30 30],...
              'Tag','23');
          
    uicontrol('Style','Edit',...            % Cell 2,4
              'String','0',...
              'Position',[260 335 30 30],...
              'Tag','24');
    uicontrol('Style','Edit',...           % Cell 2,5
              'String','0',...
              'Position',[295 335 30 30],...
              'Tag','25');
    uicontrol('Style','Edit',...           % Cell 2,6
              'String','0',...
              'Position',[330 335 30 30],...
              'Tag','26');
          
   uicontrol('Style','Edit',...             % Cell 2,7
              'String','0',...
              'Position',[380 335 30 30],...
              'Tag','27');
    uicontrol('Style','Edit',...           % Cell 2,8
              'String','0',...
              'Position',[415 335 30 30],...
              'Tag','28');
    uicontrol('Style','Edit',...           % Cell 2,9
              'String','0',...
              'Position',[450 335 30 30],...
              'Tag','29');
          
%%ROW 3
    uicontrol('Style','Edit',...           % Cell 3,1
              'String','0',...
              'Position',[140 300 30 30],...
              'Tag','31');
    uicontrol('Style','Edit',...           % Cell 3,2
              'String','0',...
              'Position',[175 300 30 30],...
              'Tag','32');
    uicontrol('Style','Edit',...           % Cell 3,3
              'String','0',...
              'Position',[210 300 30 30],...
              'Tag','33');
          
    uicontrol('Style','Edit',...            % Cell 3,4
              'String','0',...
              'Position',[260 300 30 30],...
              'Tag','34');
    uicontrol('Style','Edit',...           % Cell 3,5
              'String','0',...
              'Position',[295 300 30 30],...
              'Tag','35');
    uicontrol('Style','Edit',...           % Cell 3,6
              'String','0',...
              'Position',[330 300 30 30],...
              'Tag','36');
          
   uicontrol('Style','Edit',...             % Cell 3,7
              'String','0',...
              'Position',[380 300 30 30],...
              'Tag','37');
    uicontrol('Style','Edit',...           % Cell 3,8
              'String','0',...
              'Position',[415 300 30 30],...
              'Tag','38');
    uicontrol('Style','Edit',...           % Cell 3,9
              'String','0',...
              'Position',[450 300 30 30],...
              'Tag','39');
          
%%ROW 4
    uicontrol('Style','Edit',...           % Cell 4,1
              'String','0',...
              'Position',[140 250 30 30],...
              'Tag','41');
    uicontrol('Style','Edit',...           % Cell 4,2
              'String','0',...
              'Position',[175 250 30 30],...
              'Tag','42');
    uicontrol('Style','Edit',...           % Cell 4,3
              'String','0',...
              'Position',[210 250 30 30],...
              'Tag','43');
          
    uicontrol('Style','Edit',...            % Cell 4,4
              'String','0',...
              'Position',[260 250 30 30],...
              'Tag','44');
    uicontrol('Style','Edit',...           % Cell 4,5
              'String','0',...
              'Position',[295 250 30 30],...
              'Tag','45');
    uicontrol('Style','Edit',...           % Cell 4,6
              'String','0',...
              'Position',[330 250 30 30],...
              'Tag','46');
          
   uicontrol('Style','Edit',...             % Cell 4,7
              'String','0',...
              'Position',[380 250 30 30],...
              'Tag','47');
    uicontrol('Style','Edit',...           % Cell 4,8
              'String','0',...
              'Position',[415 250 30 30],...
              'Tag','48');
    uicontrol('Style','Edit',...           % Cell 4,9
              'String','0',...
              'Position',[450 250 30 30],...
              'Tag','49');
              
%%ROW 5
    uicontrol('Style','Edit',...           % Cell 5,1
              'String','0',...
              'Position',[140 215 30 30],...
              'Tag','51');
    uicontrol('Style','Edit',...           % Cell 5,2
              'String','0',...
              'Position',[175 215 30 30],...
              'Tag','52');
    uicontrol('Style','Edit',...           % Cell 5,3
              'String','0',...
              'Position',[210 215 30 30],...
              'Tag','53');
          
    uicontrol('Style','Edit',...            % Cell 5,4
              'String','0',...
              'Position',[260 215 30 30],...
              'Tag','54');
    uicontrol('Style','Edit',...           % Cell 5,5
              'String','0',...
              'Position',[295 215 30 30],...
              'Tag','55');
    uicontrol('Style','Edit',...           % Cell 5,6
              'String','0',...
              'Position',[330 215 30 30],...
              'Tag','56');
          
   uicontrol('Style','Edit',...             % Cell 5,7
              'String','0',...
              'Position',[380 215 30 30],...
              'Tag','57');
    uicontrol('Style','Edit',...           % Cell 5,8
              'String','0',...
              'Position',[415 215 30 30],...
              'Tag','58');
    uicontrol('Style','Edit',...           % Cell 5,9
              'String','0',...
              'Position',[450 215 30 30],...
              'Tag','59');
          
%%ROW 6
    uicontrol('Style','Edit',...           % Cell 6,1
              'String','0',...
              'Position',[140 180 30 30],...
              'Tag','61');
    uicontrol('Style','Edit',...           % Cell 6,2
              'String','0',...
              'Position',[175 180 30 30],...
              'Tag','62');
    uicontrol('Style','Edit',...           % Cell 6,3
              'String','0',...
              'Position',[210 180 30 30],...
              'Tag','63');
          
    uicontrol('Style','Edit',...            % Cell 6,4
              'String','0',...
              'Position',[260 180 30 30],...
              'Tag','64');
    uicontrol('Style','Edit',...           % Cell 6,5
              'String','0',...
              'Position',[295 180 30 30],...
              'Tag','65');
    uicontrol('Style','Edit',...           % Cell 6,6
              'String','0',...
              'Position',[330 180 30 30],...
              'Tag','66');
          
   uicontrol('Style','Edit',...             % Cell 6,7
              'String','0',...
              'Position',[380 180 30 30],...
              'Tag','67');
    uicontrol('Style','Edit',...           % Cell 6,8
              'String','0',...
              'Position',[415 180 30 30],...
              'Tag','68');
    uicontrol('Style','Edit',...           % Cell 6,9
              'String','0',...
              'Position',[450 180 30 30],...
              'Tag','69');
          
%%ROW 7
    uicontrol('Style','Edit',...           % Cell 7,1
              'String','0',...
              'Position',[140 130 30 30],...
              'Tag','71');
    uicontrol('Style','Edit',...           % Cell 7,2
              'String','0',...
              'Position',[175 130 30 30],...
              'Tag','72');
    uicontrol('Style','Edit',...           % Cell 7,3
              'String','0',...
              'Position',[210 130 30 30],...
              'Tag','73');
          
    uicontrol('Style','Edit',...            % Cell 7,4
              'String','0',...
              'Position',[260 130 30 30],...
              'Tag','74');
    uicontrol('Style','Edit',...           % Cell 7,5
              'String','0',...
              'Position',[295 130 30 30],...
              'Tag','75');
    uicontrol('Style','Edit',...           % Cell 7,6
              'String','0',...
              'Position',[330 130 30 30],...
              'Tag','76');
          
   uicontrol('Style','Edit',...             % Cell 7,7
              'String','0',...
              'Position',[380 130 30 30],...
              'Tag','77');
    uicontrol('Style','Edit',...           % Cell 7,8
              'String','0',...
              'Position',[415 130 30 30],...
              'Tag','78');
    uicontrol('Style','Edit',...           % Cell 7,9
              'String','0',...
              'Position',[450 130 30 30],...
              'Tag','79');
          
%%ROW 8
    uicontrol('Style','Edit',...           % Cell 8,1
              'String','0',...
              'Position',[140 95 30 30],...
              'Tag','81');
    uicontrol('Style','Edit',...           % Cell 8,2
              'String','0',...
              'Position',[175 95 30 30],...
              'Tag','82');
    uicontrol('Style','Edit',...           % Cell 8,3
              'String','0',...
              'Position',[210 95 30 30],...
              'Tag','83');
          
    uicontrol('Style','Edit',...            % Cell 8,4
              'String','0',...
              'Position',[260 95 30 30],...
              'Tag','84');
    uicontrol('Style','Edit',...           % Cell 8,5
              'String','0',...
              'Position',[295 95 30 30],...
              'Tag','85');
    uicontrol('Style','Edit',...           % Cell 8,6
              'String','0',...
              'Position',[330 95 30 30],...
              'Tag','86');
          
   uicontrol('Style','Edit',...             % Cell 8,7
              'String','0',...
              'Position',[380 95 30 30],...
              'Tag','87');
    uicontrol('Style','Edit',...           % Cell 8,8
              'String','0',...
              'Position',[415 95 30 30],...
              'Tag','88');
    uicontrol('Style','Edit',...           % Cell 8,9
              'String','0',...
              'Position',[450 95 30 30],...
              'Tag','89');
          
%%ROW 9
    uicontrol('Style','Edit',...           % Cell 9,1
              'String','0',...
              'Position',[140 60 30 30],...
              'Tag','91');
    uicontrol('Style','Edit',...           % Cell 9,2
              'String','0',...
              'Position',[175 60 30 30],...
              'Tag','92');
    uicontrol('Style','Edit',...           % Cell 9,3
              'String','0',...
              'Position',[210 60 30 30],...
              'Tag','93');
          
    uicontrol('Style','Edit',...            % Cell 9,4
              'String','0',...
              'Position',[260 60 30 30],...
              'Tag','94');
    uicontrol('Style','Edit',...           % Cell 9,5
              'String','0',...
              'Position',[295 60 30 30],...
              'Tag','95');
    uicontrol('Style','Edit',...           % Cell 9,6
              'String','0',...
              'Position',[330 60 30 30],...
              'Tag','96');
          
   uicontrol('Style','Edit',...             % Cell 9,7
              'String','0',...
              'Position',[380 60 30 30],...
              'Tag','97');
    uicontrol('Style','Edit',...           % Cell 9,8
              'String','0',...
              'Position',[415 60 30 30],...
              'Tag','98');
    uicontrol('Style','Edit',...           % Cell 9,9
              'String','0',...
              'Position',[450 60 30 30],...
              'Tag','99');
          
          
          
elseif strcmp(action,'start')
if strcmp(get(findobj(gcf,'Tag','Control'),'String'),'Solve!')
    %There's GOT to be an easier way to do all this...
    c11 = str2double(get(findobj(gcf,'Tag','11'),'String'));        % Cell 1,1
    c12 = str2double(get(findobj(gcf,'Tag','12'),'String'));        % Cell 1,2
    c13 = str2double(get(findobj(gcf,'Tag','13'),'String'));        % Cell 1,3
    c14 = str2double(get(findobj(gcf,'Tag','14'),'String'));        % Cell 1,4
    c15 = str2double(get(findobj(gcf,'Tag','15'),'String'));        % Cell 1,5
    c16 = str2double(get(findobj(gcf,'Tag','16'),'String'));        % Cell 1,6
    c17 = str2double(get(findobj(gcf,'Tag','17'),'String'));        % Cell 1,7
    c18 = str2double(get(findobj(gcf,'Tag','18'),'String'));        % Cell 1,8
    c19 = str2double(get(findobj(gcf,'Tag','19'),'String'));        % Cell 1,9
    c21 = str2double(get(findobj(gcf,'Tag','21'),'String'));        % Cell 2,1
    c22 = str2double(get(findobj(gcf,'Tag','22'),'String'));        % Cell 2,2
    c23 = str2double(get(findobj(gcf,'Tag','23'),'String'));        % Cell 2,3
    c24 = str2double(get(findobj(gcf,'Tag','24'),'String'));        % Cell 2,4
    c25 = str2double(get(findobj(gcf,'Tag','25'),'String'));        % Cell 2,5
    c26 = str2double(get(findobj(gcf,'Tag','26'),'String'));        % Cell 2,6
    c27 = str2double(get(findobj(gcf,'Tag','27'),'String'));        % Cell 2,7
    c28 = str2double(get(findobj(gcf,'Tag','28'),'String'));        % Cell 2,8
    c29 = str2double(get(findobj(gcf,'Tag','29'),'String'));        % Cell 2,9
    c31 = str2double(get(findobj(gcf,'Tag','31'),'String'));        % Cell 3,1
    c32 = str2double(get(findobj(gcf,'Tag','32'),'String'));        % Cell 3,2
    c33 = str2double(get(findobj(gcf,'Tag','33'),'String'));        % Cell 3,3
    c34 = str2double(get(findobj(gcf,'Tag','34'),'String'));        % Cell 3,4
    c35 = str2double(get(findobj(gcf,'Tag','35'),'String'));        % Cell 3,5
    c36 = str2double(get(findobj(gcf,'Tag','36'),'String'));        % Cell 3,6
    c37 = str2double(get(findobj(gcf,'Tag','37'),'String'));        % Cell 3,7
    c38 = str2double(get(findobj(gcf,'Tag','38'),'String'));        % Cell 3,8
    c39 = str2double(get(findobj(gcf,'Tag','39'),'String'));        % Cell 3,9
    c41 = str2double(get(findobj(gcf,'Tag','41'),'String'));        % Cell 4,1
    c42 = str2double(get(findobj(gcf,'Tag','42'),'String'));        % Cell 4,2
    c43 = str2double(get(findobj(gcf,'Tag','43'),'String'));        % Cell 4,3
    c44 = str2double(get(findobj(gcf,'Tag','44'),'String'));        % Cell 4,4
    c45 = str2double(get(findobj(gcf,'Tag','45'),'String'));        % Cell 4,5
    c46 = str2double(get(findobj(gcf,'Tag','46'),'String'));        % Cell 4,6
    c47 = str2double(get(findobj(gcf,'Tag','47'),'String'));        % Cell 4,7
    c48 = str2double(get(findobj(gcf,'Tag','48'),'String'));        % Cell 4,8
    c49 = str2double(get(findobj(gcf,'Tag','49'),'String'));        % Cell 4,9
    c51 = str2double(get(findobj(gcf,'Tag','51'),'String'));        % Cell 5,1
    c52 = str2double(get(findobj(gcf,'Tag','52'),'String'));        % Cell 5,2
    c53 = str2double(get(findobj(gcf,'Tag','53'),'String'));        % Cell 5,3
    c54 = str2double(get(findobj(gcf,'Tag','54'),'String'));        % Cell 5,4
    c55 = str2double(get(findobj(gcf,'Tag','55'),'String'));        % Cell 5,5
    c56 = str2double(get(findobj(gcf,'Tag','56'),'String'));        % Cell 5,6
    c57 = str2double(get(findobj(gcf,'Tag','57'),'String'));        % Cell 5,7
    c58 = str2double(get(findobj(gcf,'Tag','58'),'String'));        % Cell 5,8
    c59 = str2double(get(findobj(gcf,'Tag','59'),'String'));        % Cell 5,9
    c61 = str2double(get(findobj(gcf,'Tag','61'),'String'));        % Cell 6,1
    c62 = str2double(get(findobj(gcf,'Tag','62'),'String'));        % Cell 6,2
    c63 = str2double(get(findobj(gcf,'Tag','63'),'String'));        % Cell 6,3
    c64 = str2double(get(findobj(gcf,'Tag','64'),'String'));        % Cell 6,4
    c65 = str2double(get(findobj(gcf,'Tag','65'),'String'));        % Cell 6,5
    c66 = str2double(get(findobj(gcf,'Tag','66'),'String'));        % Cell 6,6
    c67 = str2double(get(findobj(gcf,'Tag','67'),'String'));        % Cell 6,7
    c68 = str2double(get(findobj(gcf,'Tag','68'),'String'));        % Cell 6,8
    c69 = str2double(get(findobj(gcf,'Tag','69'),'String'));        % Cell 6,9
    c71 = str2double(get(findobj(gcf,'Tag','71'),'String'));        % Cell 7,1
    c72 = str2double(get(findobj(gcf,'Tag','72'),'String'));        % Cell 7,2
    c73 = str2double(get(findobj(gcf,'Tag','73'),'String'));        % Cell 7,3
    c74 = str2double(get(findobj(gcf,'Tag','74'),'String'));        % Cell 7,4
    c75 = str2double(get(findobj(gcf,'Tag','75'),'String'));        % Cell 7,5
    c76 = str2double(get(findobj(gcf,'Tag','76'),'String'));        % Cell 7,6
    c77 = str2double(get(findobj(gcf,'Tag','77'),'String'));        % Cell 7,7
    c78 = str2double(get(findobj(gcf,'Tag','78'),'String'));        % Cell 7,8
    c79 = str2double(get(findobj(gcf,'Tag','79'),'String'));        % Cell 7,9
    c81 = str2double(get(findobj(gcf,'Tag','81'),'String'));        % Cell 8,1
    c82 = str2double(get(findobj(gcf,'Tag','82'),'String'));        % Cell 8,2
    c83 = str2double(get(findobj(gcf,'Tag','83'),'String'));        % Cell 8,3
    c84 = str2double(get(findobj(gcf,'Tag','84'),'String'));        % Cell 8,4
    c85 = str2double(get(findobj(gcf,'Tag','85'),'String'));        % Cell 8,5
    c86 = str2double(get(findobj(gcf,'Tag','86'),'String'));        % Cell 8,6
    c87 = str2double(get(findobj(gcf,'Tag','87'),'String'));        % Cell 8,7
    c88 = str2double(get(findobj(gcf,'Tag','88'),'String'));        % Cell 8,8
    c89 = str2double(get(findobj(gcf,'Tag','89'),'String'));        % Cell 8,9
    c91 = str2double(get(findobj(gcf,'Tag','91'),'String'));        % Cell 9,1
    c92 = str2double(get(findobj(gcf,'Tag','92'),'String'));        % Cell 9,2
    c93 = str2double(get(findobj(gcf,'Tag','93'),'String'));        % Cell 9,3
    c94 = str2double(get(findobj(gcf,'Tag','94'),'String'));        % Cell 9,4
    c95 = str2double(get(findobj(gcf,'Tag','95'),'String'));        % Cell 9,5
    c96 = str2double(get(findobj(gcf,'Tag','96'),'String'));        % Cell 9,6
    c97 = str2double(get(findobj(gcf,'Tag','97'),'String'));        % Cell 9,7
    c98 = str2double(get(findobj(gcf,'Tag','98'),'String'));        % Cell 9,8
    c99 = str2double(get(findobj(gcf,'Tag','99'),'String'));        % Cell 9,9
    
    A=[c11 c12 c13 c14 c15 c16 c17 c18 c19;c21 c22 c23 c24 c25 c26 c27 c28 c29;c31 c32 c33 c34 c35 c36 c37 c38 c39;...
       c41 c42 c43 c44 c45 c46 c47 c48 c49;c51 c52 c53 c54 c55 c56 c57 c58 c59;c61 c62 c63 c64 c65 c66 c67 c68 c69;...
       c71 c72 c73 c74 c75 c76 c77 c78 c79;c81 c82 c83 c84 c85 c86 c87 c88 c89;c91 c92 c93 c94 c95 c96 c97 c98 c99];
    
    B=SudokuCore(A);
    
    for r = 1:9
        for c = 1:9
            elename = strcat(num2str(r),num2str(c))
            set(findobj(gcf,'Tag',elename),'String',num2str(B(r,c)))
        end
    end
    set(findobj(gcf,'Tag','Control'),'String','Reset');
    
    
elseif strcmp(get(findobj(gcf,'Tag','Control'),'String'),'Reset')
    for r = 1:9
        for c = 1:9
            elename = strcat(num2str(r),num2str(c))
            set(findobj(gcf,'Tag',elename),'String','0')
        end
    end
    set(findobj(gcf,'Tag','Control'),'String','Solve!');
end
elseif strcmp(action,'about')  %display a little about box, it's really totally worthless, but I thought it was fun.
    aboutmsg=sprintf('Sudoku Solver | Version 1.0\nDesigned by Kevin Claytor.\nFor results and more examples see: http://www.owlnet.rice.edu/~kec4482/');
    msgbox(aboutmsg,'About Sudoku Solver - V 1.0')
end

return